In [1]:
import pandas as pd 
import os
import json
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import gzip

In [11]:
path_reviews = os.path.join('..','..','data','yelp','reviews.csv.gz')
reviews = pd.read_csv (path_reviews, compression='gzip')

# Extracci√≥n

In [4]:
users = pd.read_parquet('./Datasets/Yelp/user-001.parquet')

In [10]:
users

,user_id,name,review_count,yelping_since,useful,funny,cool,elite,friends,fans,...,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos
0,qVc8ODYU5SZjKXVBgXdI7w,Walker,585,2007-01-25 16:47:26,7217,1259,5994,2007,"NSCy54eWehBJyZdG2iE84w, pe42u7DcCH2QmI81NX-8qA...",267,...,65,55,56,18,232,844,467,467,239,180
1,j14WgRoU_-2ZE1aw1dXrJg,Daniel,4333,2009-01-25 04:35:42,43091,13066,27281,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2...","ueRPE0CX75ePGMqOFVj6IQ, 52oH4DrRvzzl8wh5UXyU0A...",3138,...,264,184,157,251,1847,7054,3131,3131,1521,1946
2,2WnXYQFK0hXEoTxPtV2zvg,Steph,665,2008-07-25 10:41:00,2086,1010,1003,"2009,2010,2011,2012,2013","LuO3Bn4f3rlhyHIaNfTlnA, j9B4XdHUhDfTKVecyWQgyA...",52,...,13,10,17,3,66,96,119,119,35,18
3,SZDeASXq7o05mMNLshsdIA,Gwen,224,2005-11-29 04:38:33,512,330,299,"2009,2010,2011","enx1vVPnfdNUdPho6PH_wg, 4wOcvMLtU6a9Lslggq74Vg...",28,...,4,1,6,2,12,16,26,26,10,9
4,hA5lMy-EnncsH4JoR-hFGQ,Karen,79,2007-01-05 19:40:59,29,15,7,,"PBK4q9KEEBHhFvSXCUirIw, 3FWPpM7KU1gXeOM_ZbYMbA...",1,...,1,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2105592,4QGxxakRZeOlg_qDuxmTeQ,Jennilee,38,2012-01-19 23:33:02,74,9,6,,kmwNG5LZSHFmveg6wYYdrw,0,...,1,0,0,0,1,4,0,0,1,0
2105593,tmelBbVBGAzXBVfH2u_R6g,Gerry,19,2009-06-09 16:34:54,14,5,2,,"BFYdCAMFyjYHDwesndEXEg, _9fTIqfSJc7g3V_o76XRVg...",1,...,1,0,0,0,0,1,0,0,0,0
2105594,tpBznnD6uJN3m_pJubj09w,Emily,26,2013-08-13 23:18:11,4,1,2,,"bKV3ly2MuK-K1cptMrFknQ, liel18zRoSB4tEkUP7i6Cg...",0,...,0,0,0,0,1,0,0,0,0,0
2105595,Kst_srPw7GdYydMFYdCtzw,Heatheranne,25,2015-01-10 00:06:25,21,2,5,,"dzHTk52vbGtbktRm_B-wEg, fOfFLV7IbBDN6lzARaLqdg...",0,...,0,0,0,0,0,1,0,0,0,0
2105596,mZl-mH3ZIWLRSd_FfvrXFg,Jessica,30,2015-11-30 21:10:17,27,1,17,,"pou3BbKsIozfH50rxmnMew, JT3rDC7-hprCSObnihMeHw...",3,...,0,1,0,0,0,1,0,0,1,0

## Transformaci√≥n

In [14]:
users = users[users['user_id'].isin(reviews['user_id'])]

### Divisi√≥n de datos para carga incremental

In [4]:
users['date_create_user'] = pd.to_datetime(users['yelping_since']).dt.year

users_2022 = users[users['date_create_user'] == 2022]
users = users[users['date_create_user'] < 2022]

## Carga

In [8]:
user_path = os.path.join('..','..','data','yelp','users.csv.gz')
users.to_csv (user_path, compression='gzip', index=False)

user_path_2022 = os.path.join('..','..','data','yelp','users_2022.csv.gz')
users.to_csv (user_path_2022, compression='gzip', index=False)